export const SELECT_SINGLE_PLAYER_TYPE = "SELECT_SINGLE_PLAYER_TYPE";
export const SELECT_MULTI_PLAYER_TYPE = "SELECT_MULTI_PLAYER_TYPE";
export const SELECT_PLAYER_NUMBER = "SELECT_PLAYER_NUMBER";
export const SELECT_GAME_TYPE = "SELECT_GAME_TYPE";
