export const SELECT_SINGLE_PLAYER_TYPE = "SELECT_SINGLE_PLAYER_TYPE";
export const SELECT_MULTI_PLAYER_TYPE = "SELECT_MULTI_PLAYER_TYPE";
export const SELECT_PLAYER_NUMBER = "SELECT_PLAYER_NUMBER";
export const UPDATE_PLAYER_AVAILABILITY = "UPDATE_PLAYER_AVAILABILITY";
export const SET_GAME_CONFIGS = "SET_GAME_CONFIGS";

// SP Question action constants
export const SET_SP_TRIVIA_QUESTIONS = "SET_SP_TRIVIA_QUESTIONS";
export const SET_SP_ANSWERED = "SET_SP_ANSWERED";
export const ADD_SP_ANSWER = "ADD_SP_ANSWER";
export const SET_SP_BEGIN_QUIZ = "SET_SP_BEGIN_QUIZ";
export const UNSET_SP_BEGIN_QUIZ = "UNSET_SP_BEGIN_QUIZ";

// MP Question action constants
export const SET_MP_TRIVIA_QUESTIONS = "SET_MP_TRIVIA_QUESTIONS";
export const ADD_MP_ANSWER = "ADD_MP_ANSWER";
export const SET_MP_BEGIN_QUIZ = "SET_MP_BEGIN_QUIZ";
export const UNSET_MP_BEGIN_QUIZ = "UNSET_MP_BEGIN_QUIZ";