export const RESTART_SELECTIONS = "RESTART_SELECTIONS";
export const OPEN_ONBOARDING = "OPEN_ONBOARDING";
export const CLOSE_ONBOARDING = "CLOSE_ONBOARDING";

export const SELECT_SINGLE_PLAYER_TYPE = "SELECT_SINGLE_PLAYER_TYPE";
export const SELECT_MULTI_PLAYER_TYPE = "SELECT_MULTI_PLAYER_TYPE";
export const SELECT_PLAYER_NUMBER = "SELECT_PLAYER_NUMBER";
export const UPDATE_PLAYER_AVAILABILITY = "UPDATE_PLAYER_AVAILABILITY";
export const SET_GAME_CONFIGS = "SET_GAME_CONFIGS";

// SP Question action constants
export const SET_SP_TRIVIA_QUESTIONS = "SET_SP_TRIVIA_QUESTIONS";
export const SET_SP_ANSWERED = "SET_SP_ANSWERED";
export const ADD_SP_ANSWER = "ADD_SP_ANSWER";
export const SET_SP_BEGIN_QUIZ = "SET_SP_BEGIN_QUIZ";
export const UNSET_SP_BEGIN_QUIZ = "UNSET_SP_BEGIN_QUIZ";

// MP Question action constants
export const SET_MP_QUESTIONS = "SET_MP_QUESTIONS";
export const ADD_MP_ANSWER = "ADD_MP_ANSWER";
export const START_MP_QUIZ = "START_MP_QUIZ";
export const END_MP_QUIZ = "END_MP_QUIZ";
export const UPDATE_MP_TIME = "UPDATE_MP_TIME";
export const UPDATE_MP_SCORES = "UPDATE_MP_SCORES";
export const UPDATE_SCOREBOARDS = "UPDATE_SCOREBOARDS";

