export const PLAYER_MODE = {
    SINGLE_PLAYER: "SINGLE_PLAYER",
    MULTI_PLAYER: "MULTI_PLAYER"
};

export const GAME_TYPE = {
    TIME_MODE: "TIME_MODE",
    SCORE_MODE: "SCORE_MODE"
};

export const GAME_PHASE = {
    SELECT_MULTI: "SELECT_MULTI",
    SELECT_PLAYER: "SELECT_PLAYER",
    SELECT_GAME_TYPE: "SELECT_GAME_TYPE",
    SET_CONFIGS: "SET_CONFIGS",
    PLAY_GAME: "PLAY_GAME",
    VIEW_SCORES: "VIEW_SCORES"
};